### ISSUE TITLE
`\texttt` for family code?

### ISSUE THREAD

**Issue by niruvt** [cicervlvs/langnames#11]
As of now with `\liso{brg}` we simply print our output in the `\normalfont`, but I just had a thought that maybe we can print it in `\texttt` to make it look like a code and distinguish it from the other stuff. We can keep an option to turn this behavior off or change the font. To compare, here is a screenshot.

![Screenshot_2022-09-10_22-55-12](https://user-images.githubusercontent.com/54938729/189494962-59e72a24-fa8b-47a0-bff6-a23a49135b89.png)

**Comment by cicervlvs** [comment]
As far as I know, this isn't standard in Linguistics papers, and I've never seen it used. I think this would lead to more confusion than anything else. Unless, that is, you can find examples of this font family being used in papers, in which case I will reconsider.

**Comment by niruvt** [comment]
Okay, I agree. Let's drop the idea.
