### ISSUE TITLE
expkv can also be eliminated (says the package author)

### ISSUE THREAD

**Issue by niruvt** [cicervlvs/langnames#14]
As pointed out by Jonathan, the package author of `expkv`, [here](https://topanswers.xyz/transcript?room=347&id=143222&year=2022&month=10#c143222), even the expkv dependency can be eliminated. This will only boost the package. I have implemented this with https://github.com/cicervlvs/langnames/commit/9e638da4e0b000360a8660575e9a3ca21abdcd5a.

You can release the files on CTAN. With https://github.com/cicervlvs/langnames/commit/6bd48a9e1f4b8429de439050c7196d508ae47c21 I have updated the necessary things everywhere.

**Comment by cicervlvs** [comment]
Thank you for the work. I have made a new release and sent the new version to CTAN.
