### ISSUE TITLE
add a macro to produce the code which is used by babel

### ISSUE THREAD

**Issue by andrewufrank** [cicervlvs/langnames#35]
It would be very useful to produce for a language the code which is required to make babel work with the language - i.e. a translation of the language name to the babel language code, possibly also a conversion from the iso code to the babel code. 

there may be need to add a selector for different versions of the language, e.g. ngerman vs german for a revices spelling. Several languages may have such variants. 

Thank you!

**Comment by niruvt** [comment]
@andrewufrank,

Can you suggest a use-case? As far as I can think of `babel` uses full language names at the user-end. I am failing to think of an example where `babel` asks for language code.

**Comment by niruvt** [comment]
Additionally, even if we identify a real use-case, I think it would be much better as a `babel` feature request. Imagine a user is using `babel` already and they need the language-code to be printed somewhere, I think it is too bold to assume that they will know about our package. So I suggest that you report your feature-request (with example) to [them](https://github.com/latex3/babel/issues/).

**Comment by niruvt** [comment]
What do you think @cicervlvs?

(Sorry for the multiple pings! :P)

**Comment by cicervlvs** [comment]
Hello both,

Thanks for the suggestion, @andrewufrank! I also would like to see an actual use-case for this. Would it be useful for a document which uses many different languages? Otherwise, why wouldn't you look up the babel code manually?

I'm failing to see the utility of it right now, but I might not be understanding the feature correctly.

Thanks!

**Comment by andrewufrank** [comment]
My use case is a blog I write in different languages (German, English, occasionally French or Italian), Text may include parts in other languages, which is currently not properly dealt with. The source is translated to HTML and PDF. I plan to add automatic translations in the coming months. 

Language codes play an important role; initially I added a translation from "de-CH" to "ngerman" for babel and extended such transformation ad-hoc. I also use `translate` (https://ctan.org/pkg/translator) to adapt additional text (e.g. "see on page" to the output),  which uses yet another method to identify languages and I assume there are others. Therefore I decided to use the ISO codes and need to translate for using babel, thus the suggestion.  

Indeed, it would be much simpler if babel would accept the ISO codes, as could `translate` or `polyglossia` (which uses BCP-47, similar to ISO-639). I will make the suggestion to `babel` as @niruvt  pointed out above, even though there is an open issue dealing with the German language encoding (`german` vs `ngerman`); perhaps I should switch to `polyglossia`... 

I suggest you close this  and I thank you for the discussion which helped me to see the complexity of the languaeg codes, Perhaps you could add a conversion to BCP-47, which seems just a replacemet of a dash to a underbar?

**Comment by niruvt** [comment]
@andrewufrank thanks for explaining your use-case. We will close this issue as it is clear now that our package should not get into this despite it being a necessary and important task.

A completely tangential (and unassaulted) suggestion: Don't switch from `babel`. I have had some experience with both `polyglossia` and `babel`. I have developed several things so far that involve multilingual typesetting. I haven't used `translator` ever, so can't comment on it, but `babel` is so far your best bet in LaTeX-world. It is a LuaLaTeX-oriented package; whereas `polyglossia` is a XeLaTeX-oriented one. Few years ago the situation was a little different. LuaLaTeX was buggy and was under development. At that time, `polyglossia` used to be very powerful, but slowly LuaLaTeX has gotten way ahead of XeLaTeX. There are a lot of Lua-only things already there on CTAN and I am sure nobody who works with multiple languages would like to give up on them. Also `babel` is a part of LaTeX3 project, unlike `polyglossia`. What can you do? I would suggest ask a question on question answer forums like TopAnswers (https://topanswers.xyz/tex) or StackExchange (https://tex.stackexchange.com/). If you don't get any answers, try to report the bug to `babel`, but hold on to it, switching from either of these to the other is _very_ painful and you would not want to do that at a very later stage.

**Comment by andrewufrank** [comment]
@niruvt  - Thank you very much for the warning! You saved me certainly a lot of time! Adding the ISO codes to babel is simpler and keeping my ad-hoc translation is easy.

**Comment by niruvt** [comment]
Most welcome.

Oh and sorry, I missed the following from your previous message:

> Perhaps you could add a conversion to BCP-47, which seems just a replacemet of a dash to a underbar?

Can you give an example? Sorry, I am not very familiar with language codes. I only maintain the LaTeX side of this package, rest all is the brainchild of @cicervlvs.

**Comment by andrewufrank** [comment]
@niruvt - ISO language codes -- in the format of interest here -- are written as 2 lower case characters followed by an underscore (sometimes a hyphen) followed by 2 capital characters for the country: e.g. de_CH for German as used in Switzerland (not the Swiss German dialect, which has `gsw` or `gsw_CH` as ICU code).
The IETF BCP 47 language tag (https://en.wikipedia.org/wiki/IETF_language_tag) has essentially the same structure but specified a  hyphen.  
I think it is sufficient to replace the underbar with a hyphen; probably not worth it. Packages accepting ISO language codes however should accept both hyphen and underbar (as it seems not to be specified in the ISO code).
