### ISSUE TITLE
Don't change filenames

### ISSUE THREAD

**Issue by niruvt** [cicervlvs/langnames#5]
### Continued from #4 
> >  As you have changed filenames in this commit too, it would be a significant change to your LaTeX package
> >
> I did not consider this, it was just bugging me how the naming was kind of inconsistent.

I can understand your concern. I think if only the consistency is a problem, then maybe we can revert this particular commit, make our internal commands consistent with the file-names, instead of changing our file-names following the code. Do you think we can do that?

> I can't imagine many people have this package already installed on their computers,

As soon as you release some package on CTAN, people who update their TeX Live automatically get your package. There are people out there who subscribe to CTAN announcements mailing lists. Our packages are continuously observed by the community. This is how I came to know about your package. While discussing the benchmarking process, I met another user who knew your package and was unable to compile. So yes, TeX is a small village-like-world unlike giants like R, Python😄.

**Comment by cicervlvs** [comment]
> I think if only the consistency is a problem, then maybe we can revert this particular commit, make our internal commands consistent with the file-names

This is what makes most sense, I think. I just did so.

**Comment by niruvt** [comment]
Thanks!
Looks good to me.
