### ISSUE TITLE
Why `\unskip`?

### ISSUE THREAD

**Issue by niruvt** [cicervlvs/langnames#6]
### Continued from #4
> >  Why the \unskip macro?
> >
> This was something that I noticed while initially developing the package, the command was printing without a space between it and the next word.

Look at the following example.

```
\documentclass{article}
\def\foo{foo}
\def\bar{bar\unskip}
\def\foobar#1{#1 \foo\bar}

\begin{document}
\foobar{my} is awesome.

The \bar gobbles the coming space.
\end{document}
```

`\bar` despite of having `\unskip` gobbles the following space, because that is TeX's general behavior. The primary reason to add a space after a macro is not to get a space in the document, it is to end the macro-name. Without a space it won't be a `\bar` in this case, it would be `\bargobbles` which we haven't defined. After this there are two possibilities. One is when the author does _not_ want a space after the macro and the other one is when they do want a space after it. Imagine if TeX added space after the macro in the document by default there would have been no way to not get a space after it. Hence the default behavior is such. To get a space after `\bar` in this case one would have to type:

1. `The \bar\ gobbles the coming space.`
  This will add a _breakable_ space. So if `\bar` and `gobbles` are at the end of the line TeX might break the line after `\bar`.
2. `The \bar~gobbles the coming space.`
  This will add an _unbreakable_ space. Even if these words are at the end of the line TeX will break the line before the `\bar` and keep both of them together. Typically this is used for prefixes like Dr.~Ross etc.
3. `The {\bar} gobbles the coming space.`
  We put `\bar` in a group, so the purpose of ending the macro is already solved, now we don't need a space for it, hence the space coming after it isn't gobbled. It is considered as a legit whitespace to be printed in the document. Note that this is what we have in our case. We have internal macros which we print with `\lname{arg}`, but whatever we print is already ended by the last `}`. So I don't think we need `\unskip`.
4. `The \bar{} gobbles the coming space.`
  We start and end an empty group which does nothing but end the previous macro.
6. `The \bar{ } gobbles the coming space.`
  We add a compulsory space here. It is better to avoid this approach, because it can produce two consecutive spaces when used like this `\bar{ } gobbles`.

> This stopped happening when I started using \unskip, so I haven't looked back.

Even before rebuilding the package your macros used to end with `{arg}` so I don't know where exactly could you see this behavior. You can experience this only in macros which don't have arguments.

> If you say that it can work without the command, we can also remove it. I want to see it first though haha.

I see no problem. Just try removing all the `\unskip`s from the current sty and test as many cases as you want, I suspect nothing would go wrong. Even if something goes wrong, a safer way would be to put our internal macros in a group like this `{\csname somestuff\endcsname}` (cf. example number 3).

**Comment by cicervlvs** [comment]
Thinking about it, this issue and my consequent use of `unskip` might have come about because of the key-value syntax from `xkeyval` that I was initially using, which didn't use any curly braces, so then some sort of break would have been necessary. Eventually by some refinement they probably became superfluous, but by then I had forgotten about it. I will remove them and do just a quick test (always have to test!) and push the non `unskip`ped version.

**Comment by niruvt** [comment]
>  I will remove them and do just a quick test (always have to test!) and push the non unskipped version.

Sure, I think to rest assured we will still put the internal macros in braces. That would be safest of all.

**Comment by niruvt** [comment]
So something like:

```
\newcommand*{\lname}[1]{%
  {%
    \csname langnames@langs@\langnames@cs@prefix@#1\endcsname
  }%
}
```

**Comment by cicervlvs** [comment]
Done! Safety first. Will get to the other issues tomorrow
