### ISSUE TITLE
Keep internal naming intuitive to the user.

### ISSUE THREAD

**Issue by niruvt** [cicervlvs/langnames#7]
### Continued from #4

> > The package option we set is `glottolog`, but the prefix that users are supposed to use `glot`...
> >
> Sure, we can change this.

Okay, will post a PR for this soon.

Also it's a bit tedious to post PRs, if you don't mind, I will be more than happy to co-author this package with you. LaTeX has packages, e.g., [1][1], [2][2], [3][3] which are co-maintained by multiple authors. Of course this is just a suggestion, not a demand.

  [1]: https://ctan.org/pkg/polyglossia
  [2]: https://ctan.org/pkg/menukeys
  [3]: https://ctan.org/pkg/biblatex

**Comment by niruvt** [comment]
Solved with https://github.com/cicervlvs/langnames/pull/10/commits/709b87078c21835627afd1571fde18add28d430f and https://github.com/cicervlvs/langnames/pull/10/commits/61cfc714123c7d163dbc5bee251198ba193615d5

@cicervlvs let me know what you think about my suggestion.

**Comment by cicervlvs** [comment]
I wouldn't mind to have you as a co-author, of course, given how involved you've been in the process this last week. Do you happen to know how to do that for CTAN?

I can also give you permission to commit directly to the repo. It's no problem.

**Comment by niruvt** [comment]
> I wouldn't mind to have you as a co-author, of course, given how involved you've been in the process this last week.

Okay :)

> Do you happen to know how to do that for CTAN?

Haven't done that before, maybe while submitting we will have to do something. We can add an "internal note" to not install the package directly, but first guide us about the procedure.

> I can also give you permission to commit directly to the repo. It's no problem.

Thanks I just received the access.
